"""CLI entrypoint for raw data presence checks and lightweight profiling."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from credit_risk_analytics.ingestion.csv_profiler import build_ingestion_report, write_report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate raw CSV presence and generate structural metadata."
    )
    parser.add_argument(
        "--raw-dir",
        default=str(PROJECT_ROOT / "data" / "raw"),
        help="Directory containing the raw CSV files.",
    )
    parser.add_argument(
        "--output",
        default=str(PROJECT_ROOT / "artifacts" / "ingestion" / "raw_ingestion_report.json"),
        help="Path to the JSON report generated by the audit.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    raw_dir = Path(args.raw_dir).resolve()
    output_path = Path(args.output).resolve()

    report = build_ingestion_report(raw_dir)
    write_report(report, output_path)

    print(json.dumps(report, indent=2))
    return 0 if report["table_count_found"] == report["table_count_expected"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
